services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads/avatars/:/uploads/avatars/:ro
      - ./nginx/logs:/var/log/nginx
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - '9113:9113'
    command:
      - -nginx.scrape-uri=http://nginx/status

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
